on:
  workflow_call:
    inputs: 
      environment:
        required: true
        type: string
    secrets:
      kubeconfig: 
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment
        run: |
          echo ${{ inputs.environment }}