name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  include:
    name: Update Version
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop' || github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Find where I am
        run: |
          pwd
          ls -la
          ls -la ../
          ls -la ./.github/workflows/update-version/

      - name: Update version
        uses: ./.github/workflows/update-version/
