name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  include:
    name: Update Version
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop' || github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Update version
        uses: ./.github/actions/sub-action.yaml
