name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  include:
    name: Update Version
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop' || github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Update version
        uses: ./.github/actions/update-version/
  
  deploy:
    needs: [include]
    uses: ./.github/workflows/reusable-workflow.yaml
    with: 
      environment: dev
