name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  include:
    name: Update Version
    template: .github/actions/sub-action.yml
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop' || github.event_name == 'push' && github.ref == 'refs/heads/master'
